"""Database update

Revision ID: ec3398763047
Revises: 6d6ed69a5459
Create Date: 2024-01-08 04:50:48.814955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3398763047'
down_revision: Union[str, None] = '6d6ed69a5459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('link', sa.String(), nullable=False))
    op.add_column('articles', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('articles', 'article_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_link', sa.VARCHAR(), nullable=True))
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'link')
    # ### end Alembic commands ###
